# Generated by Django 5.1.4 on 2024-12-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
