# Generated by Django 5.1.4 on 2024-12-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
